export const DAMAGE_TYPE_MAP: Record<string, string> = {
  acid: 'acid',
  bludgeoning: 'bludgeoning',
  cold: 'cold',
  fire: 'fire',
  force: 'force',
  lightning: 'lightning',
  necrotic: 'necrotic',
  piercing: 'piercing',
  poison: 'poison',
  psychic: 'psychic',
  radiant: 'radiant',
  slashing: 'slashing',
  thunder: 'thunder',
};

export const CONDITION_MAP: Record<string, string> = {
  blinded: 'blinded',
  charmed: 'charmed',
  deafened: 'deafened',
  diseased: 'diseased',
  exhaustion: 'exhaustion',
  frightened: 'frightened',
  grappled: 'grappled',
  incapacitated: 'incapacitated',
  invisible: 'invisible',
  paralyzed: 'paralyzed',
  petrified: 'petrified',
  poisoned: 'poisoned',
  prone: 'prone',
  restrained: 'restrained',
  stunned: 'stunned',
  unconscious: 'unconscious',
};

export const LANGUAGE_MAP: Record<string, string> = {
  common: 'common',
  draconic: 'draconic',
  dwarvish: 'dwarvish',
  elvish: 'elvish',
  giant: 'giant',
  gnomish: 'gnomish',
  goblin: 'goblin',
  halfling: 'halfling',
  orc: 'orc',
  abyssal: 'abyssal',
  celestial: 'celestial',
  infernal: 'infernal',
  primordial: 'primordial',
  sylvan: 'sylvan',
  undercommon: 'undercommon',
  'deep speech': 'deep',
  druidic: 'druidic',
  "thieves' cant": 'cant',
  "thieves cant": 'cant',
  aquan: 'aquan',
  auran: 'auran',
  ignan: 'ignan',
  terran: 'terran',
  gnoll: 'gnoll',
  'all languages': 'ALL',
  all: 'ALL',
};

export const SKILL_MAP: Record<string, { key: string; ability: string }> = {
  acrobatics: { key: 'acr', ability: 'dex' },
  'animal handling': { key: 'ani', ability: 'wis' },
  arcana: { key: 'arc', ability: 'int' },
  athletics: { key: 'ath', ability: 'str' },
  deception: { key: 'dec', ability: 'cha' },
  history: { key: 'his', ability: 'int' },
  insight: { key: 'ins', ability: 'wis' },
  intimidation: { key: 'itm', ability: 'cha' },
  investigation: { key: 'inv', ability: 'int' },
  medicine: { key: 'med', ability: 'wis' },
  nature: { key: 'nat', ability: 'int' },
  perception: { key: 'prc', ability: 'wis' },
  performance: { key: 'prf', ability: 'cha' },
  persuasion: { key: 'per', ability: 'cha' },
  religion: { key: 'rel', ability: 'int' },
  'sleight of hand': { key: 'slt', ability: 'dex' },
  stealth: { key: 'ste', ability: 'dex' },
  survival: { key: 'sur', ability: 'wis' },
};

export const SECTION_ACTIVATION: Record<string, string> = {
  actions: 'action',
  'bonus actions': 'bonus',
  reactions: 'reaction',
  'legendary actions': 'legendary',
  'lair actions': 'lair',
  'mythic actions': 'legendary',
};

export const FULL_ABILITY_MAP: Record<string, string> = {
  strength: 'str', dexterity: 'dex', constitution: 'con',
  intelligence: 'int', wisdom: 'wis', charisma: 'cha',
};

export const AREA_TYPE_MAP: Record<string, string> = {
  sphere: 'sphere', emanation: 'sphere', cone: 'cone',
  cube: 'cube', cylinder: 'cylinder', line: 'line',
};

export const ARMOR_NAME_MAP: Record<string, string> = {
  'padded armor': 'Padded Armor',
  'padded': 'Padded Armor',
  'leather armor': 'Leather Armor',
  'leather': 'Leather Armor',
  'studded leather armor': 'Studded Leather Armor',
  'studded leather': 'Studded Leather Armor',
  'hide armor': 'Hide Armor',
  'hide': 'Hide Armor',
  'chain shirt': 'Chain Shirt',
  'scale mail': 'Scale Mail',
  'breastplate': 'Breastplate',
  'half plate armor': 'Half Plate Armor',
  'half plate': 'Half Plate Armor',
  'ring mail': 'Ring Mail',
  'chain mail': 'Chain Mail',
  'splint armor': 'Splint Armor',
  'splint': 'Splint Armor',
  'plate armor': 'Plate Armor',
  'plate': 'Plate Armor',
  'patchwork armor': 'Patchwork Armor',
  'patchwork': 'Patchwork Armor',
  'shield': 'Shield',
  'buckler': 'Buckler',
};
